apiVersion: v1
data:
  application.yaml: |
    spring:
      devtools.add-properties: false
    application:
      config: "loaded from ConfigMap"
kind: ConfigMap
metadata:
  labels:
    app: kboot-k3d-service
    appGroup: demo
  name: kboot-k3d-service-config
  namespace: default
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: kboot-k3d-service
    appGroup: demo
    type: local
  name: kboot-k3d-pv-hostpath
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kboot-k3d-service
    appGroup: demo
  name: kboot-k3d-service
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kboot-k3d-service
    appGroup: demo
  name: kboot-k3d-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: kboot-k3d-service
      appGroup: demo
  template:
    metadata:
      labels:
        app: kboot-k3d-service
        appGroup: demo
    spec:
      containers:
      - image: kboot-k3d-service:latest
        name: kboot-k3d-service
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
      - configMap:
          name: kboot-k3d-service-config
        name: config
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: kboot-k3d-service
    appGroup: demo
  name: kboot-k3d-service
  namespace: default
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: kboot-k3d-service
        appGroup: demo
    spec:
      template:
        metadata:
          labels:
            app: kboot-k3d-service
            appGroup: demo
        spec:
          containers:
          - env:
            - name: SPRING_PROFILES_ACTIVE
              value: localDev
            - name: ENCRYPT_KEY
              valueFrom:
                secretKeyRef:
                  key: key
                  name: spring-encrypt
            image: kboot-k3d-service:latest
            imagePullPolicy: IfNotPresent
            name: kboot-k3d-service
            resources:
              limits:
                cpu: 1000m
                memory: 1Gi
              requests:
                cpu: 500m
                memory: 500Mi
            volumeMounts:
            - mountPath: /data
              name: data-volume
          restartPolicy: Never
          volumes:
          - name: data-volume
            persistentVolumeClaim:
              claimName: kboot-k3d-service
  schedule: '*/1 * * * *'
