apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: kboot-k3d-service
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: localDev
