apiVersion: batch/v1
kind: CronJob
metadata:
  name: app
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kboot-k3d-service
            env:
            - name: SPRING_PROFILES_ACTIVE
              value: localDev

