apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kboot-k3d-

resources:
- deployment.yaml
- service.yaml

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: service
  target:
    kind: Deployment
    name: .*
- patch: |-
    - op: replace
      path: /metadata/name
      value: service
  target:
    kind: Service
    name: .*
- patch: |-
    - op: replace
      path: /metadata/name
      value: service
  target:
    kind: PrometheusRule
    name: .*
- path: use-java-tool-options.yaml
- path: use-actuator-secret.yaml
- path: use-configmap.yaml
labels:
- includeSelectors: true
  pairs:
    app: kboot-k3d-service
    appGroup: demo
